### ISSUE TITLE
Добавить функциональность работы с сайтом Ларина

### ISSUE THREAD

**Issue by reacheight** [reacheight/technopsyna#15]

**Comment by MBkkt** [comment]
Примерный план:
1) Добавить команду в бота получение варианта по номеру: 
Получения варианта релизовать просто с помощью bs4:
1.1. Парсится сайт, находим ссылку на конкретный вариант
1.2. Скачиваем пдфку распарсив страницу с варианитом
1.3. Отправляем пользователю 
2) В текущую функцию проверки новых участников: добавить проверку в определенное время недели есть ли вариант на сайте номера плюс 1 к прошлому отправленному этой функцией(реализуется с помощью уже написанного кода для поиска конкретного варианта), если есть тогда качаем его с помощью уже реализованный команды плюс добавляем красивое описание по вкусу

Возможно есть несколько вариантов как реализовать вкидывание нового варианта, выбор конкретного остается за тем кто будет реализовывать, это просто один из вариантов
