### ISSUE TITLE
ParseMode = MARKDOWN ломает сообщение приветствия нового мембера техноконфы, если у него есть _ в юзернейме

### ISSUE THREAD

**Issue by reacheight** [reacheight/technopsyna#34]
Символы _ в маркдауне используются для курсива. Поэтому, если у нового мембера есть _ в юзернейме, то эти символы распарсятся как границы курсива. Это само по себе не хорошо, но если таких символов нечетное количество, то сообщение не сможет распарсится и упадёт, не отправившись, и у мембера не будет кнопки. Самое хорошее решение, которое я вижу - аккуратно экранировать _ в юзернейме.

**Comment by matobes** [comment]
Рома, привет. Ты закончил матобес?
